name: privai

services:
  app:
    build: .
    container_name: privai
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/backend
      - media_data:/app/backend/media
      - chroma_data:/app/backend/chroma_db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  sqlite_data:
  media_data:
  chroma_data:
