# Generated by Django 5.2.1 on 2025-06-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='generated_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
