# Generated by Django 5.2.1 on 2025-06-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_otpcode_generated_otp_otpcode_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
