# Generated by Django 5.2.1 on 2025-06-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_otpcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
