# Generated by Django 5.2.8 on 2026-06-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
